openapi: 3.0.3
info:
  title: RiijskAPI
  description: rijksmuseum.nl
  version: 1.0.0
servers:
- url: https://www.rijksmuseum.nl/api/en/
tags:
- name: museum
  description: Category facets
- name: topArtObjects
  description: Top art objects
paths:
  /collection/:
    get:
      tags:
      - museum
      summary: Facets List
      operationId: getRequest
      parameters:
      - name: key
        in: query
        description: Api Key
        required: true
        schema:
          type: string
      - name: q
        in: query
        description: Search request value
        required: false
        schema:
          type: string
      - name: p
        in: query
        description: Number of page
        required: true
        schema:
          type: integer
      responses:
        "200":
          description: success
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ResponseSource'
        default:
          description: enexpected error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorModel'
components:
  schemas:
    ResponseSource:
      type: object
      properties:
        elapsedMilliseconds:
          type: integer
        count:
          type: integer
        artObjects:
          type: dictionary
          items:
            $ref: '#/components/schemas/ArtObject'
        facets:
          type: array
          items:
            $ref: '#/components/schemas/FacetSource'

    ArtObject:
      required:
        - id
        - title
        - longTitle
        - principalOrFirstMaker
      type: object
      properties:
        id:
          type: string
        objectNumber:
          type: string
        title:
          type: string
        hasImage:
          type: boolean
        principalOrFirstMaker:
          type: string
        longTitle:
          type: string
        showImage:
          type: boolean
        permitDownload:
          type: boolean

    FacetSource:
      type: object
      properties:
        facets:
          type: array
          items:
            $ref: '#/components/schemas/Facet'
        name:
          type: string

    Facet:
      required:
        - key
        - value
      type: object
      properties:
        key:
          type: string
        value:
          type: integer
    ErrorModel:
      required:
      - code
      - message
      type: object
      properties:
        message:
          type: string
        code:
          maximum: 600
          minimum: 100
          type: integer
